packages:
  - 'packages/**'

catalog:
  rimraf: ^6.1.2
  rollup: ^4.57.1
  "@rollup/plugin-terser": ^0.4.4
  "@rollup/plugin-node-resolve": ^16.0.3
  typescript: ^5.7.2
  tslib: ^2.8.1
  rollup-plugin-esbuild: ^6.2.1
