export const ClothesComponent = Object.freeze({
  Head: 0, Beard: 1, Hair: 2, Torso: 3, Legs: 4, Hands: 5,
  Foot: 6, Eyes: 7, Accessories: 8, Tasks: 9, Decals: 10, Tops: 11
});

export const ColshapeType = Object.freeze({
  Sphere: "sphere", Tube: "tube", Circle: "circle",
  Rectangle: "rectangle", Cuboid: "cuboid", Polygon: "polygon"
});

export const EntityType = Object.freeze({
  Player: "player", Vehicle: "vehicle", Object: "object", Pickup: "pickup",
  Blip: "blip", Checkpoint: "checkpoint", Marker: "marker", Colshape: "colshape",
  TextLabel: "textlabel", Ped: "ped", Dummy: "dummy"
});

export const HeadOverlay = Object.freeze({
  Blemishes: 0, FacialHair: 1, Eyebrows: 2, Ageing: 3, Makeup: 4,
  Blush: 5, Complexion: 6, SunDamage: 7, Lipstick: 8, MolesFreckles: 9,
  ChestHair: 10, BodyBlemishes: 11, AddBodyBlemishes: 12
});

export const PlayerProp = Object.freeze({ Helmet: 0, Glasses: 1, EarPiece: 2 });

export const VehicleNumberPlateType = Object.freeze({
  BlueOnWhite1: 0, YellowOnBlack: 1, YellowOnBlue: 2,
  BlueOnWhite2: 3, BlueOnWhite3: 4, Yankton: 5
});

export const VehicleSeat = Object.freeze({
  Driver: 0, Passenger1: 1, Passenger2: 2, Passenger3: 3,
  Passenger4: 4, Passenger5: 5, Passenger6: 6, Passenger7: 7,
  Passenger8: 8, Passenger9: 9, Passenger10: 10, Passenger11: 11,
  Passenger12: 12, Passenger13: 13, Passenger14: 14, Passenger15: 15,
  Passenger16: 16
});

export const Weather = Object.freeze({
  ExtraSunny: 0, Clear: 1, Clouds: 2, Smog: 3, Foggy: 4,
  Overcast: 5, Rain: 6, Thunder: 7, Clearing: 8, Neutral: 9,
  Snow: 10, Blizzard: 11, Snowlight: 12, Xmas: 13, Halloween: 14
});

export const ScreenshotType = Object.freeze({ JPEG: 0, PNG: 1, BMP: 2 });

export const Controls = Object.freeze({
  INPUT_NEXT_CAMERA: 0, INPUT_LOOK_LR: 1, INPUT_LOOK_UD: 2,
  INPUT_LOOK_UP_ONLY: 3, INPUT_LOOK_DOWN_ONLY: 4, INPUT_LOOK_LEFT_ONLY: 5,
  INPUT_LOOK_RIGHT_ONLY: 6, INPUT_CINEMATIC_SLOWMO: 7, INPUT_SCRIPTED_FLY_UD: 8,
  INPUT_SCRIPTED_FLY_LR: 9, INPUT_SCRIPTED_FLY_ZUP: 10, INPUT_SCRIPTED_FLY_ZDOWN: 11,
  INPUT_WEAPON_WHEEL_UD: 12, INPUT_WEAPON_WHEEL_LR: 13, INPUT_WEAPON_WHEEL_NEXT: 14,
  INPUT_WEAPON_WHEEL_PREV: 15, INPUT_SELECT_NEXT_WEAPON: 16, INPUT_SELECT_PREV_WEAPON: 17,
  INPUT_SKIP_CUTSCENE: 18, INPUT_CHARACTER_WHEEL: 19, INPUT_MULTIPLAYER_INFO: 20,
  INPUT_SPRINT: 21, INPUT_JUMP: 22, INPUT_ENTER: 23, INPUT_ATTACK: 24, INPUT_AIM: 25,
  INPUT_LOOK_BEHIND: 26, INPUT_PHONE: 27, INPUT_SPECIAL_ABILITY: 28,
  INPUT_SPECIAL_ABILITY_SECONDARY: 29, INPUT_MOVE_LR: 30, INPUT_MOVE_UD: 31,
  INPUT_MOVE_UP_ONLY: 32, INPUT_MOVE_DOWN_ONLY: 33, INPUT_MOVE_LEFT_ONLY: 34,
  INPUT_MOVE_RIGHT_ONLY: 35, INPUT_DUCK: 36, INPUT_SELECT_WEAPON: 37,
  INPUT_PICKUP: 38, INPUT_SNIPER_ZOOM: 39, INPUT_SNIPER_ZOOM_IN_ONLY: 40,
  INPUT_SNIPER_ZOOM_OUT_ONLY: 41, INPUT_SNIPER_ZOOM_IN_SECONDARY: 42,
  INPUT_SNIPER_ZOOM_OUT_SECONDARY: 43, INPUT_COVER: 44, INPUT_RELOAD: 45,
  INPUT_TALK: 46, INPUT_DETONATE: 47, INPUT_HUD_SPECIAL: 48,
  INPUT_ARREST: 49, INPUT_ACCURATE_AIM: 50, INPUT_CONTEXT: 51,
  INPUT_CONTEXT_SECONDARY: 52, INPUT_WEAPON_SPECIAL: 53, INPUT_WEAPON_SPECIAL_TWO: 54,
  INPUT_DIVE: 55, INPUT_DROP_WEAPON: 56, INPUT_DROP_AMMO: 57,
  INPUT_THROW_GRENADE: 58, INPUT_VEH_MOVE_LR: 59, INPUT_VEH_MOVE_UD: 60,
  INPUT_VEH_MOVE_UP_ONLY: 61, INPUT_VEH_MOVE_DOWN_ONLY: 62,
  INPUT_VEH_MOVE_LEFT_ONLY: 63, INPUT_VEH_MOVE_RIGHT_ONLY: 64,
  INPUT_VEH_SPECIAL: 65, INPUT_VEH_GUN_LR: 66, INPUT_VEH_GUN_UD: 67,
  INPUT_VEH_AIM: 68, INPUT_VEH_ATTACK: 69, INPUT_VEH_ATTACK2: 70,
  INPUT_VEH_ACCELERATE: 71, INPUT_VEH_BRAKE: 72, INPUT_VEH_DUCK: 73,
  INPUT_VEH_HEADLIGHT: 74, INPUT_VEH_EXIT: 75, INPUT_VEH_HANDBRAKE: 76,
  INPUT_VEH_HOTWIRE_LEFT: 77, INPUT_VEH_HOTWIRE_RIGHT: 78,
  INPUT_VEH_LOOK_BEHIND: 79, INPUT_VEH_CIN_CAM: 80, INPUT_VEH_NEXT_RADIO: 81,
  INPUT_VEH_PREV_RADIO: 82, INPUT_VEH_NEXT_RADIO_TRACK: 83,
  INPUT_VEH_PREV_RADIO_TRACK: 84, INPUT_VEH_RADIO_WHEEL: 85,
  INPUT_VEH_HORN: 86, INPUT_VEH_FLY_THROTTLE_UP: 87,
  INPUT_VEH_FLY_THROTTLE_DOWN: 88, INPUT_VEH_FLY_YAW_LEFT: 89,
  INPUT_VEH_FLY_YAW_RIGHT: 90, INPUT_VEH_PASSENGER_AIM: 91,
  INPUT_VEH_PASSENGER_ATTACK: 92, INPUT_VEH_SPECIAL_ABILITY_FRANKLIN: 93,
  INPUT_VEH_STUNT_UD: 94, INPUT_VEH_CINEMATIC_UD: 95,
  INPUT_VEH_CINEMATIC_UP_ONLY: 96, INPUT_VEH_CINEMATIC_DOWN_ONLY: 97,
  INPUT_VEH_CINEMATIC_LR: 98, INPUT_VEH_SELECT_NEXT_WEAPON: 99,
  INPUT_VEH_SELECT_PREV_WEAPON: 100, INPUT_VEH_ROOF: 101,
  INPUT_VEH_JUMP: 102, INPUT_VEH_GRAPPLING_HOOK: 103,
  INPUT_VEH_SHUFFLE: 104, INPUT_VEH_DROP_PROJECTILE: 105,
  INPUT_VEH_MOUSE_CONTROL_OVERRIDE: 106, INPUT_VEH_FLY_ROLL_LR: 107,
  INPUT_VEH_FLY_ROLL_LEFT_ONLY: 108, INPUT_VEH_FLY_ROLL_RIGHT_ONLY: 109,
  INPUT_VEH_FLY_PITCH_UD: 110, INPUT_VEH_FLY_PITCH_UP_ONLY: 111,
  INPUT_VEH_FLY_PITCH_DOWN_ONLY: 112, INPUT_VEH_FLY_UNDERCARRIAGE: 113,
  INPUT_VEH_FLY_ATTACK: 114, INPUT_VEH_FLY_SELECT_NEXT_WEAPON: 115,
  INPUT_VEH_FLY_SELECT_PREV_WEAPON: 116, INPUT_VEH_FLY_SELECT_TARGET_LEFT: 117,
  INPUT_VEH_FLY_SELECT_TARGET_RIGHT: 118, INPUT_VEH_FLY_VERTICAL_FLIGHT_MODE: 119,
  INPUT_VEH_FLY_DUCK: 120, INPUT_VEH_FLY_ATTACK_CAMERA: 121,
  INPUT_VEH_FLY_MOUSE_CONTROL_OVERRIDE: 122, INPUT_VEH_SUB_TURN_LR: 123,
  INPUT_VEH_SUB_TURN_LEFT_ONLY: 124, INPUT_VEH_SUB_TURN_RIGHT_ONLY: 125,
  INPUT_VEH_SUB_PITCH_UD: 126, INPUT_VEH_SUB_PITCH_UP_ONLY: 127,
  INPUT_VEH_SUB_PITCH_DOWN_ONLY: 128, INPUT_VEH_SUB_THROTTLE_UP: 129,
  INPUT_VEH_SUB_THROTTLE_DOWN: 130, INPUT_VEH_SUB_ASCEND: 131,
  INPUT_VEH_SUB_DESCEND: 132, INPUT_VEH_SUB_TURN_HARD_LEFT: 133,
  INPUT_VEH_SUB_TURN_HARD_RIGHT: 134, INPUT_VEH_PUSHBIKE_PEDAL: 135,
  INPUT_VEH_PUSHBIKE_SPRINT: 136, INPUT_VEH_PUSHBIKE_FRONT_BRAKE: 137,
  INPUT_VEH_PUSHBIKE_REAR_BRAKE: 138, INPUT_MELEE_ATTACK_LIGHT: 140,
  INPUT_MELEE_ATTACK_HEAVY: 141, INPUT_MELEE_ATTACK_ALTERNATE: 142,
  INPUT_MELEE_BLOCK: 143, INPUT_PARACHUTE_DEPLOY: 144,
  INPUT_PARACHUTE_DETACH: 145, INPUT_PARACHUTE_TURN_LR: 146,
  INPUT_PARACHUTE_TURN_LEFT_ONLY: 147, INPUT_PARACHUTE_TURN_RIGHT_ONLY: 148,
  INPUT_PARACHUTE_PITCH_UD: 149, INPUT_PARACHUTE_PITCH_UP_ONLY: 150,
  INPUT_PARACHUTE_PITCH_DOWN_ONLY: 151, INPUT_PARACHUTE_BRAKE_LEFT: 152,
  INPUT_PARACHUTE_BRAKE_RIGHT: 153, INPUT_PARACHUTE_SMOKE: 154,
  INPUT_PARACHUTE_PRECISION_LANDING: 155, INPUT_MAP: 156,
  INPUT_SELECT_WEAPON_UNARMED: 157, INPUT_SELECT_WEAPON_MELEE: 158,
  INPUT_SELECT_WEAPON_HANDGUN: 159, INPUT_SELECT_WEAPON_SHOTGUN: 160,
  INPUT_SELECT_WEAPON_SMG: 161, INPUT_SELECT_WEAPON_AUTO_RIFLE: 162,
  INPUT_SELECT_WEAPON_SNIPER: 163, INPUT_SELECT_WEAPON_HEAVY: 164,
  INPUT_SELECT_WEAPON_SPECIAL: 165, INPUT_SELECT_CHARACTER_MICHAEL: 166,
  INPUT_SELECT_CHARACTER_FRANKLIN: 167, INPUT_SELECT_CHARACTER_TREVOR: 168,
  INPUT_SELECT_CHARACTER_MULTIPLAYER: 169, INPUT_SAVE_REPLAY_CLIP: 170,
  INPUT_SPECIAL_ABILITY_PC: 171, INPUT_CELLPHONE_UP: 172,
  INPUT_CELLPHONE_DOWN: 173, INPUT_CELLPHONE_LEFT: 174,
  INPUT_CELLPHONE_RIGHT: 175, INPUT_CELLPHONE_SELECT: 176,
  INPUT_CELLPHONE_CANCEL: 177, INPUT_CELLPHONE_OPTION: 178,
  INPUT_CELLPHONE_EXTRA_OPTION: 179, INPUT_CELLPHONE_SCROLL_FORWARD: 180,
  INPUT_CELLPHONE_SCROLL_BACKWARD: 181, INPUT_CELLPHONE_CAMERA_FOCUS_LOCK: 182,
  INPUT_CELLPHONE_CAMERA_GRID: 183, INPUT_CELLPHONE_CAMERA_SELFIE: 184,
  INPUT_CELLPHONE_CAMERA_DOF: 185, INPUT_CELLPHONE_CAMERA_EXPRESSION: 186,
  INPUT_FRONTEND_DOWN: 187, INPUT_FRONTEND_UP: 188,
  INPUT_FRONTEND_LEFT: 189, INPUT_FRONTEND_RIGHT: 190,
  INPUT_FRONTEND_RDOWN: 191, INPUT_FRONTEND_RUP: 192,
  INPUT_FRONTEND_RLEFT: 193, INPUT_FRONTEND_RRIGHT: 194,
  INPUT_FRONTEND_AXIS_X: 195, INPUT_FRONTEND_AXIS_Y: 196,
  INPUT_FRONTEND_RIGHT_AXIS_X: 197, INPUT_FRONTEND_RIGHT_AXIS_Y: 198,
  INPUT_FRONTEND_PAUSE: 199, INPUT_FRONTEND_PAUSE_ALTERNATE: 200,
  INPUT_FRONTEND_ACCEPT: 201, INPUT_FRONTEND_CANCEL: 202,
  INPUT_FRONTEND_X: 203, INPUT_FRONTEND_Y: 204,
  INPUT_FRONTEND_LB: 205, INPUT_FRONTEND_RB: 206,
  INPUT_FRONTEND_LT: 207, INPUT_FRONTEND_RT: 208,
  INPUT_FRONTEND_LS: 209, INPUT_FRONTEND_RS: 210,
  INPUT_FRONTEND_LEADERBOARD: 211, INPUT_FRONTEND_SOCIAL_CLUB: 212,
  INPUT_FRONTEND_SOCIAL_CLUB_SECONDARY: 213, INPUT_FRONTEND_DELETE: 214,
  INPUT_FRONTEND_ENDSCREEN_ACCEPT: 215, INPUT_FRONTEND_ENDSCREEN_EXPAND: 216,
  INPUT_FRONTEND_SELECT: 217, INPUT_SCRIPT_LEFT_AXIS_X: 218,
  INPUT_SCRIPT_LEFT_AXIS_Y: 219, INPUT_SCRIPT_RIGHT_AXIS_X: 220,
  INPUT_SCRIPT_RIGHT_AXIS_Y: 221, INPUT_SCRIPT_RUP: 222,
  INPUT_SCRIPT_RDOWN: 223, INPUT_SCRIPT_RLEFT: 224, INPUT_SCRIPT_RRIGHT: 225,
  INPUT_SCRIPT_LB: 226, INPUT_SCRIPT_RB: 227, INPUT_SCRIPT_LT: 228,
  INPUT_SCRIPT_RT: 229, INPUT_SCRIPT_LS: 230, INPUT_SCRIPT_RS: 231,
  INPUT_SCRIPT_PAD_UP: 232, INPUT_SCRIPT_PAD_DOWN: 233,
  INPUT_SCRIPT_PAD_LEFT: 234, INPUT_SCRIPT_PAD_RIGHT: 235,
  INPUT_SCRIPT_SELECT: 236, INPUT_CURSOR_ACCEPT: 237,
  INPUT_CURSOR_CANCEL: 238, INPUT_CURSOR_X: 239, INPUT_CURSOR_Y: 240,
  INPUT_CURSOR_SCROLL_UP: 241, INPUT_CURSOR_SCROLL_DOWN: 242,
  INPUT_ENTER_CHEAT_CODE: 243, INPUT_INTERACTION_MENU: 244,
  INPUT_MP_TEXT_CHAT_ALL: 245, INPUT_MP_TEXT_CHAT_TEAM: 246,
  INPUT_MP_TEXT_CHAT_FRIENDS: 247, INPUT_MP_TEXT_CHAT_CREW: 248,
  INPUT_PUSH_TO_TALK: 249, INPUT_CREATOR_LS: 250, INPUT_CREATOR_RS: 251,
  INPUT_CREATOR_LT: 252, INPUT_CREATOR_RT: 253, INPUT_CREATOR_MENU_TOGGLE: 254,
  INPUT_CREATOR_ACCEPT: 255, INPUT_CREATOR_DELETE: 256,
  INPUT_ATTACK2: 257, INPUT_RAPPEL_JUMP: 258, INPUT_RAPPEL_LONG_JUMP: 259,
  INPUT_RAPPEL_SMASH_WINDOW: 260, INPUT_PREV_WEAPON: 261,
  INPUT_NEXT_WEAPON: 262, INPUT_MELEE_ATTACK1: 263, INPUT_MELEE_ATTACK2: 264,
  INPUT_WHISTLE: 265, INPUT_MOVE_LEFT: 266, INPUT_MOVE_RIGHT: 267,
  INPUT_MOVE_UP: 268, INPUT_MOVE_DOWN: 269, INPUT_LOOK_LEFT: 270,
  INPUT_LOOK_RIGHT: 271, INPUT_LOOK_UP: 272, INPUT_LOOK_DOWN: 273,
  INPUT_SNIPER_ZOOM_IN: 274, INPUT_SNIPER_ZOOM_OUT: 275,
  INPUT_SNIPER_ZOOM_IN_ALTERNATE: 276, INPUT_SNIPER_ZOOM_OUT_ALTERNATE: 277,
  INPUT_VEH_MOVE_LEFT: 278, INPUT_VEH_MOVE_RIGHT: 279,
  INPUT_VEH_MOVE_UP: 280, INPUT_VEH_MOVE_DOWN: 281,
  INPUT_VEH_GUN_LEFT: 282, INPUT_VEH_GUN_RIGHT: 283,
  INPUT_VEH_GUN_UP: 284, INPUT_VEH_GUN_DOWN: 285,
  INPUT_VEH_LOOK_LEFT: 286, INPUT_VEH_LOOK_RIGHT: 287,
  INPUT_REPLAY_START_STOP_RECORDING: 288, INPUT_REPLAY_START_STOP_RECORDING_SECONDARY: 289,
  INPUT_SCALED_LOOK_LR: 290, INPUT_SCALED_LOOK_UD: 291,
  INPUT_SCALED_LOOK_UP_ONLY: 292, INPUT_SCALED_LOOK_DOWN_ONLY: 293,
  INPUT_SCALED_LOOK_LEFT_ONLY: 294, INPUT_SCALED_LOOK_RIGHT_ONLY: 295,
  INPUT_REPLAY_MARKER_DELETE: 296, INPUT_REPLAY_CLIP_DELETE: 297,
  INPUT_REPLAY_PAUSE: 298, INPUT_REPLAY_REWIND: 299,
  INPUT_REPLAY_FFWD: 300, INPUT_REPLAY_NEWMARKER: 301,
  INPUT_REPLAY_RECORD: 302, INPUT_REPLAY_SCREENSHOT: 303,
  INPUT_REPLAY_HIDEHUD: 304, INPUT_REPLAY_STARTPOINT: 305,
  INPUT_REPLAY_ENDPOINT: 306, INPUT_REPLAY_ADVANCE: 307,
  INPUT_REPLAY_BACK: 308, INPUT_REPLAY_TOOLS: 309,
  INPUT_REPLAY_RESTART: 310, INPUT_REPLAY_SHOWHOTKEY: 311,
  INPUT_REPLAY_CYCLEMARKERLEFT: 312, INPUT_REPLAY_CYCLEMARKERRIGHT: 313,
  INPUT_REPLAY_FOVINCREASE: 314, INPUT_REPLAY_FOVDECREASE: 315,
  INPUT_REPLAY_CAMERAUP: 316, INPUT_REPLAY_CAMERADOWN: 317,
  INPUT_REPLAY_SAVE: 318, INPUT_REPLAY_TOGGLETIME: 319,
  INPUT_REPLAY_TOGGLETIPS: 320, INPUT_REPLAY_PREVIEW: 321,
  INPUT_REPLAY_TOGGLE_TIMELINE: 322, INPUT_REPLAY_TIMELINE_PICKUP_CLIP: 323,
  INPUT_REPLAY_TIMELINE_DUPLICATE_CLIP: 324, INPUT_REPLAY_TIMELINE_PLACE_CLIP: 325,
  INPUT_REPLAY_CTRL: 326, INPUT_REPLAY_TIMELINE_SAVE: 327,
  INPUT_REPLAY_PREVIEW_AUDIO: 328, INPUT_VEH_DRIVE_LOOK: 329,
  INPUT_VEH_DRIVE_LOOK2: 330, INPUT_VEH_FLY_ATTACK2: 331,
  INPUT_RADIO_WHEEL_UD: 332, INPUT_RADIO_WHEEL_LR: 333,
  INPUT_VEH_SLOWMO_UD: 334, INPUT_VEH_SLOWMO_UP_ONLY: 335,
  INPUT_VEH_SLOWMO_DOWN_ONLY: 336, INPUT_VEH_HYDRAULICS_CONTROL_TOGGLE: 337,
  INPUT_VEH_HYDRAULICS_CONTROL_LEFT: 338, INPUT_VEH_HYDRAULICS_CONTROL_RIGHT: 339,
  INPUT_VEH_HYDRAULICS_CONTROL_UP: 340, INPUT_VEH_HYDRAULICS_CONTROL_DOWN: 341,
  INPUT_VEH_HYDRAULICS_CONTROL_UD: 342, INPUT_VEH_HYDRAULICS_CONTROL_LR: 343,
  INPUT_SWITCH_VISOR: 344, INPUT_VEH_MELEE_HOLD: 345,
  INPUT_VEH_MELEE_LEFT: 346, INPUT_VEH_MELEE_RIGHT: 347,
  INPUT_MAP_POI: 348, INPUT_REPLAY_SNAPMATIC_PHOTO: 349,
  INPUT_VEH_CAR_JUMP: 350, INPUT_VEH_ROCKET_BOOST: 351,
  INPUT_VEH_FLY_BOOST: 352, INPUT_VEH_PARACHUTE: 353,
  INPUT_VEH_BIKE_WINGS: 354, INPUT_VEH_FLY_BOMB_BAY: 355,
  INPUT_VEH_FLY_COUNTER: 356, INPUT_VEH_TRANSFORM: 357
});

export const Marker = Object.freeze({
  UpsideDownCone: 0, VerticalCylinder: 1, ThickChevronUp: 2, ThinChevronUp: 3,
  CheckeredFlagRect: 4, CheckeredFlagCircle: 5, VerticleCircle: 6, PlaneModel: 7,
  LostMCDark: 8, LostMCLight: 9, Number0: 10, Number1: 11, Number2: 12,
  Number3: 13, Number4: 14, Number5: 15, Number6: 16, Number7: 17,
  Number8: 18, Number9: 19, ChevronUpx1: 20, ChevronUpx2: 21, ChevronUpx3: 22,
  HorizontalCircleFat: 23, ReplayIcon: 24, HorizontalCircleSkinny: 25,
  HorizontalCircleSkinnyArrow: 26, HorizontalSplitArrowCircle: 27,
  DebugSphere: 28, DollarSign: 29, HorizontalBars: 30, WolfHead: 31,
  QuestionMark: 32, PlaneSymbol: 33, HelicopterSymbol: 34,
  BoatSymbol: 35, CarSymbol: 36, MotorcycleSymbol: 37,
  BikeSymbol: 38, TruckSymbol: 39, ParachuteSymbol: 40,
  SawbladeSymbol: 41, RampSymbol: 42, Ring: 43
});

export const Explosions = Object.freeze({
  Grenade: 0, GrenadeLauncher: 1, StickyBomb: 2, Molotov: 3, Rocket: 4,
  TankShell: 5, HiOctane: 6, Car: 7, Plane: 8, PetrolPump: 9,
  Bike: 10, DirSteam: 11, DirFlame: 12, DirWaterHydrant: 13, DirGasCanister: 14,
  Boat: 15, ShipDestroy: 16, Truck: 17, Bullet: 18, SmokeGGrenade: 19,
  Bzgas: 20, Flare: 21, GasCanister: 22, Extinguisher: 23, ProgrammableAr: 24,
  Train: 25, Barrel: 26, Propane: 27, Blimp: 28, DirFlameExplode: 29,
  Tanker: 30, PlaneRocket: 31, VehicleBullet: 32, GasTank: 33, Firework: 34,
  Snowball: 35, ProxMine: 36, ValkyrieCannon: 37, AirDefence: 38, PipeBomb: 39,
  VehicleMine: 40, ExplosiveAmmo: 41, ApcShell: 42, BombCluster: 43, BombGas: 44,
  BombIncendiary: 45, BombStandard: 46, Torpedo: 47, TorpedoUnderwater: 48,
  BombushkaCannon: 49, BombushkaBomb: 50, BombClusterSecondary: 51,
  HunterBarrage: 52, HunterCannon: 53, RogueCannon: 54, MineUnderwater: 55,
  OrbitalCannon: 56, BombStandardWide: 57, ExplosiveAmmoShotgun: 58,
  Oppressor2Cannon: 59, MortarKinetic: 60, VehicleMineKinetic: 61,
  VehicleMineEmp: 62, VehicleMineSpike: 63, VehicleMineSlick: 64,
  VehicleMineTar: 65, ScriptDrone: 66, Raygun: 67, BuriedMine: 68,
  ScriptMissile: 69, RcTankRocket: 70, BombWater: 71, BombWaterSecondary: 72,
});

export const Weapons = Object.freeze({
  Unarmed:         0x92A27487,
  Knife:           0x99B507EA,
  Nightstick:      0x678B81B1,
  Hammer:          0x4E875F73,
  Bat:             0x958A4A8F,
  Crowbar:         0x84BD7BFD,
  GolfClub:        0x440E4788,
  Bottle:          0xF9E6AA4B,
  Dagger:          0x92A27487,
  Hatchet:         0xF9DCBF2D,
  KnuckleDuster:   0xD8DF3C3C,
  Machete:         0xDD5DF8D9,
  Flashlight:      0x8BB05FD7,
  SwitchBlade:     0xDFE37640,
  BattleAxe:       0x2578D5B3,
  PoolCue:         0x94117305,
  StoneHatchet:    0x3813FC08,
  Pistol:          0x1B06D571,
  Pistol50:        0x99AEEB3B,
  ApPistol:        0x22D8FE39,
  StunGun:         0x3656C8C1,
  FlareGun:        0x47757124,
  MarksmanPistol:  0xDC4DB296,
  HeavyPistol:     0xD205520E,
  VintagePistol:   0x083839C4,
  CeramicPistol:   0x2B5EF4AB,
  NavyRevolver:    0x917F6C8C,
  MicroSmg:        0x13532244,
  Smg:             0x2BE6766B,
  SmgMk2:          0x78A97CD0,
  AssaultSmg:      0xEFE7E2DF,
  MiniSmg:         0xBD248B55,
  MachinePistol:   0xDB1AA450,
  CombatPdw:       0x0A3D4D34,
  PumpShotgun:     0x1D073A89,
  PumpShotgunMk2:  0x555AF99A,
  SawnOffShotgun:  0x7846A318,
  BullpupShotgun:  0x9D61E50F,
  Musket:          0xA89CB99E,
  HeavyShotgun:    0x3AABBBAA,
  DoubleBarrelShotgun: 0xAF113F99,
  AssaultRifle:    0xBFEFFF6D,
  AssaultRifleMk2: 0x394F415C,
  CarbineRifle:    0x83BF0278,
  CarbineRifleMk2: 0xFAD1F1C9,
  AdvancedRifle:   0xAF113F99,
  SpecialCarbine:  0xC0A3098D,
  SpecialCarbineMk2: 0x969C3D67,
  BullpupRifle:    0x7F229F94,
  BullpupRifleMk2: 0x84D6FAFD,
  CompactRifle:    0x624FE830,
  MG:              0x9D07F764,
  CombatMG:        0x7FD62962,
  CombatMGMk2:     0xDBBD7280,
  GusenbergSweeper: 0x61012683,
  SniperRifle:     0x05FC3C11,
  HeavySniperMk2:  0xA914799,
  MarksmanRifle:   0xC734385A,
  MarksmanRifleMk2: 0x6A6C02E0,
  GrenadeLauncher: 0xA284510B,
  GrenadeLauncherSmoke: 0x4DD2DC56,
  RPG:             0xB1CA77B1,
  Minigun:         0x42BF8A85,
  Firework:        0x7F7497E5,
  Railgun:         0x6D544C99,
  HomingLauncher:  0x63AB0442,
  CompactGrenadeLauncher: 0x781FE4A,
  Widowmaker:      0x05C4EDCE,
  Grenade:         0x93E220BD,
  StickyBomb:      0x2C3731D9,
  ProximityMines:  0xAB564B93,
  BZGas:           0xA0973D5E,
  Molotov:         0x24B17070,
  FireExtinguisher: 0x060EC506,
  Flare:           0x497FACC3,
  Ball:            0x23C9F95C,
  SmokeGrenade:    0xFDBC5B25,
  Snowball:        0x34A67B97,
  PipeBomb:        0xBA45E8B8,
  Parachute:       0xFBAB5776,
  NightVision:     0x42DF1E9A,
  UpNAtomizer:     0xBFEFFF6D,
});

export const InputGroup = Object.freeze({
  GenericGamepad:       0,
  GenericKeyboard:      1,
  GamepadFallbackLeft:  2,
  GamepadFallbackRight: 3,
  Move:                 4,
  Look:                 5,
  Wheel:                6,
  Aim:                  7,
  Script:               8,
  ScriptLeftStick:      9,
  ScriptRightStick:     10,
  ScriptButtons:        11,
  ScriptDPad:           12,
  ScriptShoulders:      13,
  ScriptTriggers:       14,
  ScriptBumpers:        15,
  Vehicle:              16,
  VehicleSubTask:       17,
  VehicleHeli:          18,
  VehicleArmed:         19,
  VehicleLook:          20,
  VehicleMoveAll:       21,
  VehicleFly:           22,
  VehicleFlySubTask:    23,
  VehicleSub:           24,
  VehicleSubSubTask:    25,
  VehicleSpecial:       26,
  Parachute:            27,
  Selectweapon:         28,
  SelectcharacterPC:    29,
  SelectcharacterConsole: 30,
  Frontend:             31,
  FrontendExtra:        32,
  CursorSimple:         33,
});

export const CauseOfDeath = Object.freeze({
  Unknown:       0x00000000,
  Unarmed:       0x92A27487,
  Knife:         0x99B507EA,
  Bat:           0x958A4A8F,
  Pistol:        0x1B06D571,
  Shotgun:       0x1D073A89,
  Rifle:         0xBFEFFF6D,
  SMG:           0x2BE6766B,
  Sniper:        0x05FC3C11,
  Explosion:     0x93E220BD,
  Burning:       0x24B17070,
  Vehicle:       0xA4DF76F1,
  Drowning:      0x6D68A6B9,
  Fall:          0x73B080A8,
  Suicide:       0xA8B8B5A2,
});

export const Console = Object.freeze({
  Verbosity: Object.freeze({ None: 0, Error: 1, Warning: 2, Info: 3, Debug: 4 }),
});

export const Voice = Object.freeze({
  BASSFXChan: Object.freeze({
    BASSFXCHAN_DEFAULT: 0, BASSFXCHAN_1: 1, BASSFXCHAN_2: 2,
    BASSFXCHAN_3: 3, BASSFXCHAN_4: 4, BASSFXCHAN_5: 5,
    BASSFXCHAN_6: 6, BASSFXCHAN_7: 7, BASSFXCHAN_8: 8,
    BASSFXCHAN_9: 9, BASSFXCHAN_10: 10, BASSFXCHAN_11: 11,
    BASSFXCHAN_12: 12, BASSFXCHAN_13: 13, BASSFXCHAN_14: 14,
    BASSFXCHAN_15: 15, BASSFXCHAN_16: 16, BASSFXCHAN_17: 17,
    BASSFXCHAN_18: 18, BASSFXCHAN_19: 19, BASSFXCHAN_20: 20,
    BASSFXCHAN_21: 21, BASSFXCHAN_22: 22, BASSFXCHAN_23: 23,
    BASSFXCHAN_24: 24, BASSFXCHAN_25: 25, BASSFXCHAN_26: 26,
    BASSFXCHAN_27: 27, BASSFXCHAN_28: 28, BASSFXCHAN_29: 29,
    BASSFXCHAN_30: 30, BASSFXCHAN_31: 31,
  }),
  BASSFXType: Object.freeze({
    None: 0, Chorus: 1, Compressor: 2, Distortion: 3, Echo: 4,
    Flanger: 5, Gargle: 6, I3DL2Reverb: 7, ParamEQ: 8,
    Reverb: 9, Rotate: 10, Volume: 11,
  }),
  BASSFXPhase: Object.freeze({
    Neg180: 0, Neg90: 1, Zero: 2, Pos90: 3, Pos180: 4,
  }),
});

export const Hud = Object.freeze({
  ComponentType: Object.freeze({
    HUD: 0, WANTED_STARS: 1, WEAPON_ICON: 2, CASH: 3, MP_CASH: 4, MP_MESSAGE: 5,
    VEHICLE_NAME: 6, AREA_NAME: 7, VEHICLE_CLASS: 8, STREET_NAME: 9, HELP_TEXT: 10,
    FLOATING_HELP_TEXT_1: 11, FLOATING_HELP_TEXT_2: 12, CASH_CHANGE: 13, RETICLE: 14,
    SUBTITLE_TEXT: 15, RADIO_STATIONS: 16, SAVING_GAME: 17, GAME_STREAM: 18,
    WEAPON_WHEEL: 19, WEAPON_WHEEL_STATS: 20, HUD_COMPONENTS: 21, HUD_WEAPONS: 22,
  }),
  Color: Object.freeze({
    PureWhite: 0, White: 1, Black: 2, Grey: 3, LightGrey: 4, DarkGrey: 5,
    Red: 6, RedLight: 7, RedDark: 8, Blue: 9, BlueLight: 10, BlueDark: 11,
    Yellow: 12, YellowLight: 13, YellowDark: 14, Orange: 15, OrangeLight: 16,
    OrangeDark: 17, Green: 18, GreenLight: 19, GreenDark: 20, Purple: 21,
    PurpleLight: 22, PurpleDark: 23, Pink: 24,
  }),
  Style: Object.freeze({
    Default: 0, ShoutText: 1, ShoutTextNoFlash: 2, Streamed: 3, Whisper: 4,
  }),
  CheckpointType: Object.freeze({
    CylinderSingleArrow: 0, CylinderDoubleArrow: 1, CylinderTripleArrow: 2,
    CylinderCycleArrow: 3, CylinderCheckerboard: 4, CylinderWrench: 5,
    CylinderSingleArrow2: 6, CylinderDoubleArrow2: 7, CylinderTripleArrow2: 8,
    CylinderCycleArrow2: 9, CylinderCheckerboard2: 10, CylinderWrench2: 11,
    Ring: 45, Empty: 46,
  }),
  Notification: Object.freeze({
    Default: 0, Bubble: 1, Mention: 2, Reply: 3, Reputation: 4,
  }),
  WeaponIcon: Object.freeze({
    Unarmed: 0, Pistol: 1, Knife: 2,
  }),
});

export const Camera = Object.freeze({
  GraphTypes: Object.freeze({
    Linear: 0, SinAccelDecel: 1, Accel: 2, Decel: 3, SlowIn: 4, SlowOut: 5,
    SlowInOut: 6, QuadraticIn: 7, QuadraticOut: 8, QuadraticInOut: 9,
    CubicIn: 10, CubicOut: 11, CubicInOut: 12, QuarticIn: 13, QuarticOut: 14,
    QuarticInOut: 15, QuinticIn: 16, QuinticOut: 17, QuinticInOut: 18,
    CircularIn: 19, CircularOut: 20, CircularInOut: 21,
  }),
});

export const Notification = Object.freeze({
  IconType: Object.freeze({
    Default: 0, ChatBox: 1, EMail: 2, AddFriendRequest: 3, RightJumpingArrow: 7,
    RPIcon: 8, DollarIcon: 9,
  }),
});

export const Alarms = Object.freeze({
  POLICE_STATION_ALARMS: "POLICE_STATION_ALARMS",
  PRISON_ALARMS: "PRISON_ALARMS",
  PORT_OF_LS_ALARMS: "PORT_OF_LS_ALARMS",
  JEWEL_STORE_HEIST_ALARMS: "JEWEL_STORE_HEIST_ALARMS",
  FIB_FLOOR_49_ALARMS: "FIB_FLOOR_49_ALARMS",
  FIB_FLOOR_53_ALARMS: "FIB_FLOOR_53_ALARMS",
  AGENCY_HEIST_FIB_TOWER_ALARMS: "AGENCY_HEIST_FIB_TOWER_ALARMS",
  PALETO_BAY_SHERIFF_BUILDING_ALARMS: "PALETO_BAY_SHERIFF_BUILDING_ALARMS",
  PORT_OF_LS_HEIST_SHIP_ALARMS: "PORT_OF_LS_HEIST_SHIP_ALARMS",
  PORT_OF_LS_HEIST_TRUCK_ALARMS: "PORT_OF_LS_HEIST_TRUCK_ALARMS",
});

export const Props = Object.freeze({
  Helmet: 0,
  Glasses: 1,
  EarPiece: 2,
  Watch: 6,
  Bracelet: 7,
});

export const PropDamage = Object.freeze({
  None: 0, Minor: 1, Moderate: 2, Major: 3, Destroyed: 4,
});

export const Pickups = Object.freeze({
  WEAPON_PISTOL: 0xF26B25C9,
  WEAPON_COMBATPISTOL: 0x8967B4F3,
  WEAPON_APPISTOL: 0x3B5235F1,
  WEAPON_PISTOL50: 0x26F067AB,
  WEAPON_MICROSMG: 0x1EFEC9B5,
  WEAPON_SMG: 0x3D49BFA6,
  WEAPON_ASSAULTSMG: 0xC04AC069,
  WEAPON_ASSAULTRIFLE: 0x32A95357,
  WEAPON_CARBINERIFLE: 0x4ED13EAF,
  WEAPON_ADVANCEDRIFLE: 0xF7FD4309,
  WEAPON_MG: 0x4EA98CB1,
  WEAPON_COMBATMG: 0x515E646A,
  WEAPON_PUMPSHOTGUN: 0x8F0FDE0D,
  WEAPON_SAWNOFFSHOTGUN: 0xD32C720B,
  WEAPON_ASSAULTSHOTGUN: 0xCB80F9DF,
  WEAPON_BULLPUPSHOTGUN: 0x6BF52A1E,
  WEAPON_SNIPERRIFLE: 0xC394F24F,
  WEAPON_HEAVYSNIPER: 0xE2BCBFD1,
  WEAPON_GRENADELAUNCHER: 0xC5043DDC,
  WEAPON_RPG: 0x4D36C349,
  WEAPON_MINIGUN: 0xCA80D31A,
  WEAPON_GRENADE: 0x5E8E7AE6,
  WEAPON_STICKYBOMB: 0x445C4D6A,
  WEAPON_SMOKEGRENADE: 0x82B362F2,
  WEAPON_MOLOTOV: 0x1BBA0BE3,
  WEAPON_PETROLCAN: 0xC69DE3FF,
  HEALTH_STANDARD: 0x8F707C18,
  ARMOUR_STANDARD: 0x4BFB42D1,
  MONEY_CASE: 0xCE6FDD3B,
  MONEY_WALLET: 0x113E5862,
  MONEY_PURSE: 0x1E9A99F8,
  MONEY_DEP_BAG: 0xB1F05A40,
  MONEY_PAPER_BAG: 0x36F721A8,
  MONEY_SECURITY_CASE: 0x36DB8F02,
  MONEY_VARIABLE: 0xDB60F560,
  MONEY_MED_BAG: 0x14568F28,
  VEHICLE_HEALTH_STANDARD: 0x142B9AC4,
});

export const Scripts = Object.freeze({
  main: "main",
  main_persistent: "main_persistent",
  freemode: "freemode",
  shop_controller: "shop_controller",
  selector: "selector",
  cellphone_controller: "cellphone_controller",
  pause_menu: "pause_menu",
  appcamera: "appcamera",
  appcontacts: "appcontacts",
  appmessages: "appmessages",
  apptextmessage: "apptextmessage",
});

export const Peds = Object.freeze({
  FreemodeMale: 0x705E61F2,
  FreemodeFemale: 0x9C9EFFD8,
  Michael: 0x0D7114C9,
  Franklin: 0x9B22DBAF,
  Trevor: 0x9B810FA2,
  Cop: 0x5E3DA4A4,
  Sheriff: 0xB3F3EE34,
  Swat: 0xBD86F77B,
  Paramedic: 0x6886266A,
  Fireman: 0x8FC4AB7,
  Trucker: 0x7F12D8DA,
  Mechanic: 0x90EE6483,
  Hooker: 0x4584D188,
  Construction: 0x96621E1C,
  PaparazziMale: 0xC03DBDB3,
});

export const Vehicle = Object.freeze({
  Bones: Object.freeze({
    chassis: "chassis",
    chassis_dummy: "chassis_dummy",
    chassis_Control: "chassis_Control",
    seat_dside_f: "seat_dside_f",
    seat_pside_f: "seat_pside_f",
    seat_dside_r: "seat_dside_r",
    seat_pside_r: "seat_pside_r",
    seat_dside_r1: "seat_dside_r1",
    seat_pside_r1: "seat_pside_r1",
    seat_dside_r2: "seat_dside_r2",
    seat_pside_r2: "seat_pside_r2",
    door_dside_f: "door_dside_f",
    door_pside_f: "door_pside_f",
    door_dside_r: "door_dside_r",
    door_pside_r: "door_pside_r",
    handle_dside_f: "handle_dside_f",
    handle_pside_f: "handle_pside_f",
    handle_dside_r: "handle_dside_r",
    handle_pside_r: "handle_pside_r",
    windscreen: "windscreen",
    windscreen_r: "windscreen_r",
    window_lf: "window_lf",
    window_rf: "window_rf",
    window_lr: "window_lr",
    window_rr: "window_rr",
    bonnet: "bonnet",
    boot: "boot",
    exhaust: "exhaust",
    engine: "engine",
    wheel_lf: "wheel_lf",
    wheel_rf: "wheel_rf",
    wheel_lr: "wheel_lr",
    wheel_rr: "wheel_rr",
    wheel_lm1: "wheel_lm1",
    wheel_rm1: "wheel_rm1",
    bumper_f: "bumper_f",
    bumper_r: "bumper_r",
    wing_lf: "wing_lf",
    wing_rf: "wing_rf",
    headlight_l: "headlight_l",
    headlight_r: "headlight_r",
    taillight_l: "taillight_l",
    taillight_r: "taillight_r",
    indicator_lf: "indicator_lf",
    indicator_rf: "indicator_rf",
    indicator_lr: "indicator_lr",
    indicator_rr: "indicator_rr",
    brakelight_l: "brakelight_l",
    brakelight_r: "brakelight_r",
    brakelight_m: "brakelight_m",
    reversinglight_l: "reversinglight_l",
    reversinglight_r: "reversinglight_r",
    extralight_1: "extralight_1",
    extralight_2: "extralight_2",
    extralight_3: "extralight_3",
    extralight_4: "extralight_4",
    petrolcap: "petrolcap",
    petroltank: "petroltank",
    petroltank_l: "petroltank_l",
    petroltank_r: "petroltank_r",
    steeringwheel: "steeringwheel",
    hbgrip_l: "hbgrip_l",
    hbgrip_r: "hbgrip_r",
    siren1: "siren1",
    siren2: "siren2",
    spoiler: "spoiler",
    misc_a: "misc_a", misc_b: "misc_b", misc_c: "misc_c", misc_d: "misc_d",
    misc_e: "misc_e", misc_f: "misc_f", misc_g: "misc_g", misc_h: "misc_h",
  }),
  ModType: Object.freeze({
    Spoiler: 0, FrontBumper: 1, RearBumper: 2, SideSkirt: 3, Exhaust: 4,
    Chassis: 5, Grille: 6, Hood: 7, Fender: 8, RightFender: 9, Roof: 10,
    Engine: 11, Brakes: 12, Transmission: 13, Horns: 14, Suspension: 15,
    Armor: 16, FrontWheels: 23, BackWheels: 24,
    PlateHolder: 25, VanityPlate: 26, TrimDesign: 27, Ornament: 28,
    DashBoard: 29, DialDesign: 30, Speakers: 32, Seats: 33,
    SteeringWheel: 33, ShiftLever: 34, Plaques: 35, Hydraulics: 38,
    EngineBlock: 39, AirFilter: 40, Struts: 41, ArchCover: 42, Aerials: 43,
    Trim: 44, Tank: 45, Windows: 46, Livery: 48,
  }),
  Class: Object.freeze({
    Compacts: 0, Sedans: 1, SUVs: 2, Coupes: 3, Muscle: 4, SportsClassics: 5,
    Sports: 6, Super: 7, Motorcycles: 8, OffRoad: 9, Industrial: 10, Utility: 11,
    Vans: 12, Cycles: 13, Boats: 14, Helicopters: 15, Planes: 16, Service: 17,
    Emergency: 18, Military: 19, Commercial: 20, Trains: 21,
  }),
});
