import { Vector3 } from "@ragemp-fivem-bridge/shared";
import { PlayerMpPool } from "./Pools/PlayerMpPool";
import { ObjectMpPool } from "./Pools/ObjectMpPool";
import { BlipMpPool } from "./Pools/BlipMpPool";
import { ColshapeMpPool } from "./Pools/ColshapeMpPool";
import { CheckpointMpPool } from "./Pools/CheckpointMpPool";
import { VehicleMpPool } from "./Pools/VehicleMpPool";
import { PedMpPool } from "./Pools/PedMpPool";
import { CameraMpPool } from "./Pools/CameraMpPool";
import { BrowserMpPool } from "./Pools/BrowserMpPool";
import { PickupMpPool } from "./Pools/PickupMpPool";
import { DummyMpPool } from "./Pools/DummyMpPool";
import { MarkerMpPool } from "./Pools/MarkerMpPool";
import { TextLabelMpPool } from "./Pools/TextLabelMpPool";
import { EventManager } from "./Events/EventManager";
import { KeyManager } from "./Keys/KeyManager";
import { GuiMp } from "./Gui";
import { ConsoleMp } from "./Console";
import { StorageMp } from "./Storage";
import { DiscordMp } from "./Discord";
import { NametagsMp } from "./Nametags";
import { RaycastingMp } from "./Raycasting";
import { VoiceChatMp } from "./VoiceChat";
import { UserMp } from "./User";
import { SystemMp } from "./System";
import { GameMp } from "./Game";
import { PluginManager } from "./Plugins/PluginManager";
import * as Enums from "./Enums";

export class Mp {
  Vector3 = Vector3;
  enums = Enums;
  players = new PlayerMpPool();
  objects = new ObjectMpPool();
  blips = new BlipMpPool();
  colshapes = new ColshapeMpPool();
  checkpoints = new CheckpointMpPool();
  vehicles = new VehicleMpPool();
  peds = new PedMpPool();
  cameras = new CameraMpPool();
  browsers = new BrowserMpPool();
  pickups = new PickupMpPool();
  dummies = new DummyMpPool();
  markers = new MarkerMpPool();
  labels = new TextLabelMpPool();
  events = new EventManager();
  keys = new KeyManager();
  gui = new GuiMp();
  console = new ConsoleMp();
  storage = new StorageMp();
  discord = new DiscordMp();
  nametags = new NametagsMp();
  raycasting = new RaycastingMp();
  voiceChat = new VoiceChatMp();
  user = new UserMp();
  system = new SystemMp();
  game = new GameMp();
  plugins = new PluginManager();
}
