import { Vector3, Entity } from "@ragemp-fivem-bridge/shared";
import { PlayerMpPool } from "./Pools/PlayerMpPool";
import { ObjectMpPool } from "./Pools/ObjectMpPool";
import { BlipMpPool } from "./Pools/BlipMpPool";
import { ColshapeMpPool } from "./Pools/ColshapeMpPool";
import { CheckpointMpPool } from "./Pools/CheckpointMpPool";
import { VehicleMpPool } from "./Pools/VehicleMpPool";
import { PedMpPool } from "./Pools/PedMpPool";
import { CameraMpPool } from "./Pools/CameraMpPool";
import { BrowserMpPool } from "./Pools/BrowserMpPool";
import { PickupMpPool } from "./Pools/PickupMpPool";
import { DummyMpPool } from "./Pools/DummyMpPool";
import { MarkerMpPool } from "./Pools/MarkerMpPool";
import { TextLabelMpPool } from "./Pools/TextLabelMpPool";
import { EventManager } from "./Events/EventManager";
import { KeyManager } from "./Keys/KeyManager";
import { GuiMp } from "./Gui";
import { ConsoleMp } from "./Console";
import { StorageMp } from "./Storage";
import { DiscordMp } from "./Discord";
import { NametagsMp } from "./Nametags";
import { RaycastingMp } from "./Raycasting";
import { VoiceChatMp } from "./VoiceChat";
import { UserMp } from "./User";
import { SystemMp } from "./System";
import { GameMp } from "./Game";
import { PluginManager } from "./Plugins/PluginManager";
import { PlayerMp } from "./Entities/PlayerMp";
import { VehicleMp } from "./Entities/VehicleMp";
import { ObjectMp } from "./Entities/ObjectMp";
import { BlipMp } from "./Entities/BlipMp";
import { ColshapeMp } from "./Entities/ColshapeMp";
import { CheckpointMp } from "./Entities/CheckpointMp";
import { MarkerMp } from "./Entities/MarkerMp";
import { TextLabelMp } from "./Entities/TextLabelMp";
import { PedMp } from "./Entities/PedMp";
import { DummyMp } from "./Entities/DummyMp";
import { CameraMp } from "./Entities/CameraMp";
import { BrowserMp } from "./Entities/BrowserMp";
import * as Enums from "./Enums";

export class Mp {
  Vector3 = Vector3;
  enums = Enums;

  Entity = Entity;
  Player = PlayerMp;
  Vehicle = VehicleMp;
  Object = ObjectMp;
  Blip = BlipMp;
  Colshape = ColshapeMp;
  Checkpoint = CheckpointMp;
  Marker = MarkerMp;
  TextLabel = TextLabelMp;
  Ped = PedMp;
  Dummy = DummyMp;
  Camera = CameraMp;
  Browser = BrowserMp;

  players = new PlayerMpPool();
  objects = new ObjectMpPool();
  blips = new BlipMpPool();
  colshapes = new ColshapeMpPool();
  checkpoints = new CheckpointMpPool();
  vehicles = new VehicleMpPool();
  peds = new PedMpPool();
  cameras = new CameraMpPool();
  browsers = new BrowserMpPool();
  pickups = new PickupMpPool();
  dummies = new DummyMpPool();
  markers = new MarkerMpPool();
  labels = new TextLabelMpPool();
  events = new EventManager();
  keys = new KeyManager();
  gui = new GuiMp();
  console = new ConsoleMp();
  storage = new StorageMp();
  discord = new DiscordMp();
  nametags = new NametagsMp();
  raycasting = new RaycastingMp();
  voiceChat = new VoiceChatMp();
  user = new UserMp();
  system = new SystemMp();
  game = new GameMp();
  plugins = new PluginManager();
}
