export const Vehicle = Object.freeze({
  Bones: Object.freeze({
    chassis: "chassis",
    chassis_dummy: "chassis_dummy",
    chassis_Control: "chassis_Control",
    seat_dside_f: "seat_dside_f",
    seat_pside_f: "seat_pside_f",
    seat_dside_r: "seat_dside_r",
    seat_pside_r: "seat_pside_r",
    seat_dside_r1: "seat_dside_r1",
    seat_pside_r1: "seat_pside_r1",
    seat_dside_r2: "seat_dside_r2",
    seat_pside_r2: "seat_pside_r2",
    door_dside_f: "door_dside_f",
    door_pside_f: "door_pside_f",
    door_dside_r: "door_dside_r",
    door_pside_r: "door_pside_r",
    handle_dside_f: "handle_dside_f",
    handle_pside_f: "handle_pside_f",
    handle_dside_r: "handle_dside_r",
    handle_pside_r: "handle_pside_r",
    windscreen: "windscreen",
    windscreen_r: "windscreen_r",
    window_lf: "window_lf",
    window_rf: "window_rf",
    window_lr: "window_lr",
    window_rr: "window_rr",
    bonnet: "bonnet",
    boot: "boot",
    exhaust: "exhaust",
    engine: "engine",
    wheel_lf: "wheel_lf",
    wheel_rf: "wheel_rf",
    wheel_lr: "wheel_lr",
    wheel_rr: "wheel_rr",
    wheel_lm1: "wheel_lm1",
    wheel_rm1: "wheel_rm1",
    bumper_f: "bumper_f",
    bumper_r: "bumper_r",
    wing_lf: "wing_lf",
    wing_rf: "wing_rf",
    headlight_l: "headlight_l",
    headlight_r: "headlight_r",
    taillight_l: "taillight_l",
    taillight_r: "taillight_r",
    indicator_lf: "indicator_lf",
    indicator_rf: "indicator_rf",
    indicator_lr: "indicator_lr",
    indicator_rr: "indicator_rr",
    brakelight_l: "brakelight_l",
    brakelight_r: "brakelight_r",
    brakelight_m: "brakelight_m",
    reversinglight_l: "reversinglight_l",
    reversinglight_r: "reversinglight_r",
    extralight_1: "extralight_1",
    extralight_2: "extralight_2",
    extralight_3: "extralight_3",
    extralight_4: "extralight_4",
    petrolcap: "petrolcap",
    petroltank: "petroltank",
    petroltank_l: "petroltank_l",
    petroltank_r: "petroltank_r",
    steeringwheel: "steeringwheel",
    hbgrip_l: "hbgrip_l",
    hbgrip_r: "hbgrip_r",
    siren1: "siren1",
    siren2: "siren2",
    spoiler: "spoiler",
    misc_a: "misc_a", misc_b: "misc_b", misc_c: "misc_c", misc_d: "misc_d",
    misc_e: "misc_e", misc_f: "misc_f", misc_g: "misc_g", misc_h: "misc_h",
  }),
  ModType: Object.freeze({
    Spoiler: 0, FrontBumper: 1, RearBumper: 2, SideSkirt: 3, Exhaust: 4,
    Chassis: 5, Grille: 6, Hood: 7, Fender: 8, RightFender: 9, Roof: 10,
    Engine: 11, Brakes: 12, Transmission: 13, Horns: 14, Suspension: 15,
    Armor: 16, FrontWheels: 23, BackWheels: 24,
    PlateHolder: 25, VanityPlate: 26, TrimDesign: 27, Ornament: 28,
    DashBoard: 29, DialDesign: 30, Speakers: 32, Seats: 33,
    SteeringWheel: 33, ShiftLever: 34, Plaques: 35, Hydraulics: 38,
    EngineBlock: 39, AirFilter: 40, Struts: 41, ArchCover: 42, Aerials: 43,
    Trim: 44, Tank: 45, Windows: 46, Livery: 48,
  }),
  Class: Object.freeze({
    Compacts: 0, Sedans: 1, SUVs: 2, Coupes: 3, Muscle: 4, SportsClassics: 5,
    Sports: 6, Super: 7, Motorcycles: 8, OffRoad: 9, Industrial: 10, Utility: 11,
    Vans: 12, Cycles: 13, Boats: 14, Helicopters: 15, Planes: 16, Service: 17,
    Emergency: 18, Military: 19, Commercial: 20, Trains: 21,
  }),
});

export const VehicleSeat = Object.freeze({
  Driver: 0, Passenger1: 1, Passenger2: 2, Passenger3: 3,
  Passenger4: 4, Passenger5: 5, Passenger6: 6, Passenger7: 7,
  Passenger8: 8, Passenger9: 9, Passenger10: 10, Passenger11: 11,
  Passenger12: 12, Passenger13: 13, Passenger14: 14, Passenger15: 15,
  Passenger16: 16
});

export const VehicleNumberPlateType = Object.freeze({
  BlueOnWhite1: 0, YellowOnBlack: 1, YellowOnBlue: 2,
  BlueOnWhite2: 3, BlueOnWhite3: 4, Yankton: 5
});
